-- SQL khusus untuk membuat ulang tabel star_alumni dengan kolom lengkap
DROP TABLE IF EXISTS star_alumni;

CREATE TABLE star_alumni (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  nis TEXT,
  nisn TEXT,
  username TEXT NOT NULL,
  password TEXT,
  grade TEXT,
  class TEXT,
  lastMood TEXT,
  attendanceRate REAL,
  totalSessions INTEGER,
  riskLevel TEXT,
  email TEXT,
  phone TEXT,
  instagram TEXT,
  linkedin TEXT,
  parentName TEXT,
  parentPhone TEXT,
  address TEXT,
  status TEXT,
  photo TEXT,
  isLocked INTEGER DEFAULT 0,
  graduationYear INTEGER,
  graduationClass TEXT,
  alumniStatus TEXT,
  universityName TEXT,
  degreeLevel TEXT,
  studyProgram TEXT,
  companyName TEXT,
  workUnit TEXT,
  nickname TEXT,
  birthPlace TEXT,
  birthDate TEXT,
  gender TEXT,
  religion TEXT,
  familyStatus TEXT,
  birthOrder INTEGER,
  juniorHighOrigin TEXT,
  acceptedClassX TEXT,
  fatherName TEXT,
  fatherJob TEXT,
  fatherPhone TEXT,
  motherName TEXT,
  motherJob TEXT,
  motherPhone TEXT,
  hasGuardian INTEGER DEFAULT 0,
  guardianName TEXT,
  guardianJob TEXT,
  guardianPhone TEXT,
  addressStreet TEXT,
  addressRtRw TEXT,
  addressVillage TEXT,
  addressDistrict TEXT,
  addressRegency TEXT,
  addressProvince TEXT,
  isKM INTEGER DEFAULT 0,
  alumniNumber TEXT,
  dateCreated TEXT
);
